[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor & Upload Settings
upload_speed = 921600
monitor_speed = 115200

; Compiler & LVGL Flags
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I include
    -D CORE_DEBUG_LEVEL=3

; Library Dependencies
lib_deps =
    lvgl/lvgl @ ^9.2.2
    lovyan03/LovyanGFX @ ^1.1.16
